source 'https://rubygems.org'

gem 'rails'

gem 'devise'
gem 'sqlite3'
gem 'state_machine', '~> 1.2.0'

gem 'sprockets-rails', github: 'rails/sprockets-rails'
gem 'coffee-rails',    github: 'rails/coffee-rails'
gem 'sass-rails',      github: 'rails/sass-rails'

gem 'bootstrap-sass', github: 'thomas-mcdonald/bootstrap-sass'

gem 'faker'
gem 'uglifier'

gem 'jquery-rails'
gem 'jbuilder', '~> 1.0.1'

gem 'the_role', "~> 2.5"
  # path: '../../'

gem 'the_role_bootstrap3_ui',
  github: 'the-teacher/the_role_bootstrap3_ui',
  branch: 'master'

group :test do
  gem 'factory_girl_rails', '~> 4.0'
  gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git', tag: 'v1.0.0'

  gem 'rspec', '2.14.1'
  gem 'rspec-core', '2.14.4'
  gem 'rspec-rails', '2.14.0'
end