source 'https://rubygems.org'

gem 'rails', github: 'rails/rails', branch: 'v4.0.0.rc1'
gem 'arel',  github: 'rails/arel'

gem 'sqlite3'
gem "state_machine", "~> 1.2.0"
gem 'devise', git: "https://github.com/plataformatec/devise.git", branch: 'rails4'

gem 'sprockets-rails', github: 'rails/sprockets-rails'
gem 'coffee-rails',    github: 'rails/coffee-rails'
gem 'sass-rails',      github: 'rails/sass-rails'
gem 'bootstrap-sass', '~> 2.3.1.0'

gem 'jquery-rails'
gem 'jbuilder', '~> 1.0.1'

gem 'the_role' , path: '../../'
gem 'haml' ,     git: 'https://github.com/haml/haml.git', tag: '4.0.1'

group :development, :test do
  gem 'faker'
  gem 'database_cleaner', git: "https://github.com/bmabey/database_cleaner.git", tag: "v1.0.0"
  gem "factory_girl_rails", "~> 4.0"

  gem "rspec",              git: "git://github.com/rspec/rspec.git"
  gem "rspec-rails",        git: "git://github.com/rspec/rspec-rails.git"
  gem "rspec-core",         git: "git://github.com/rspec/rspec-core.git"
  gem "rspec-expectations", git: "git://github.com/rspec/rspec-expectations.git"
  gem "rspec-mocks",        git: "git://github.com/rspec/rspec-mocks.git"
end

group :test do
  gem "rake", "~> 10.0.4"
end

# gem 'rails',     path: '/home/the_teacher/rails/rails4/the_role/spec/rails'
# gem 'arel',      github: 'rails/arel'

# gem 'sqlite3'
# gem 'sprockets-rails', github: 'rails/sprockets-rails'
# gem 'sass-rails', github: 'rails/sass-rails'
# gem 'coffee-rails', github: 'rails/coffee-rails'
# gem 'uglifier', '>= 1.3.0'

# gem 'jquery-rails'
# gem 'turbolinks'
# gem 'jbuilder', '~> 1.2'

# group :doc do
#   gem 'sdoc', require: false
# end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
